{{- if (index .Values "gpu-operator" "enabled") }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-selinux-apply-policy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      k8s-app: nvidia-selinux-policy
  template:
    metadata:
      labels:
        k8s-app: nvidia-selinux-policy
    spec:
      hostPID: true
      containers:
      - image: registry.cern.ch/kubernetes/ops:0.3.0
        name: selinux-policy-sleep
        args:
        - sleep inf
        command:
        - /bin/sh
        - -c
      initContainers:
      # check https://gitlab.cern.ch/kubernetes/automation/releases/cern-magnum/-/issues/16 for why this is needed
      - image: registry.cern.ch/magnum/fedora:36
        name: selinux-policy-apply
        command: ["/bin/bash", "-c", "semodule -i /usr/share/selinux/allow_module_load.pp"]
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /usr/share/selinux/allow_module_load.pp
          name: nvidia-selinux-policy
          subPath: allow_module_load.pp
        - mountPath: /usr/libexec/selinux/hll/pp
          name: libexec-hll
        - mountPath: /usr/sbin
          name: usrsbin
        - mountPath: /dev
          name: dev
        - mountPath: /etc
          name: etc
        - mountPath: /var/run
          name: varrun
        - mountPath: /sys
          name: sys
      nodeSelector:
        feature.node.kubernetes.io/pci-10de.present: "true"
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: nvidia-selinux-policy
        configMap:
          name: nvidia-selinux-policy
      - hostPath:
          path: /usr/libexec/selinux/hll/pp
          type: ""
        name: libexec-hll
      - hostPath:
          path: /dev
          type: ""
        name: dev
      - hostPath:
          path: /usr/sbin
          type: ""
        name: usrsbin
      - hostPath:
          path: /sys
          type: ""
        name: sys
      - hostPath:
          path: /var/run
          type: ""
        name: varrun
      - hostPath:
          path: /etc
          type: ""
        name: etc

{{- end }}
